### ISSUE TITLE
Prozkoumat moznost US Embassy Small Grants Program

### ISSUE THREAD

**Issue by aleszoulek** [pyvec/zapojse#46] opened 2016-11-02 12:23 UTC
https://cz.usembassy.gov/education-culture/small-grants-program/

Mozna pro proplaceni cest US keynote speakerum do Cech?

**Comment by kvbik** [comment] 2016-11-02 12:24
thx to @jackiekazil for letting us know

**Comment by aleszoulek** [comment] 2016-11-02 12:26
In 2015, the grant also supported:
Czechitas — Digital Literacy for Women — IT courses for women

So we can ask them about the details?

**Comment by honzajavorek** [comment] 2016-11-03 09:36
O tomto mi říkal i @ricco386 na speaker's dinner!

**Comment by jackiekazil** [comment] 2016-11-04 10:17
I learned from some information today after visiting the American Cultural center. 

Here are some tips... 
- Be concrete -- be very clear about what you want to do and why
- Be brief -- there are lots of applications, so limit your request to the most relevant information 
- English counts -- Because your application will be reviewed by English and Czech speakers
- Outreach -- Projects with a larger impact are considered stronger
- Co-Financing - Projects that are co-financed are considered stronger
- Budget -- Present a balanced, detailed and well thought through budget
- American Expert -- Projects with an American expert are more interesting!
- Applications should fit into one of the initiatives. Here are a few... 
  - Environment, Science, and Technology
  - Gender Equality 
  - Human Rights, Minority Integration and strengthening of civil society

There are deadlines about 3 times per year. 
Next one is December, then March, but I am not certain. 

The Czechitas grant was part of a specific initiative around one deadline with women. This type of focused deadline could happen again, but not necessarily. 

I hope this helps!

**Comment by kvbik** [comment] 2016-12-15 16:30
We've met Jeanne and discussed this with her. We should send her draft of the application ASAP. /cc @benabraham

**Comment by honzajavorek** [comment] 2016-12-16 20:38
Status: @benabraham and me reviewed it today and the draft is a bit more polished. Dan will maybe play with coloring for next couple of hours to please his OCD/ADHD (don't confuse with AC/DC) and then you two will send it to Jeanne. @lspdv promised to look at some of the unclear sections over the weekend.

**Comment by honzajavorek** [comment] 2017-01-19 13:19
Status: The embassy confirmed the application got delivered and they told us they'll give us a decision until the end of January. I'm not sure how much publicly we will want to communicate the outcome of this effort and there's nothing else we can do at this moment, so I'm closing this issue now :) 

Thank you everyone involved, it was a great ride! Many thanks to @benabraham in the first place for his endless efforts and unexpected ability to laser focus on one thing and to coordinate all the efforts to deliver the final documents 👌 

May the 🇺🇸 be with us!

**Closed as completed by honzajavorek** 2017-01-19 13:19 UTC

**Comment by jackiekazil** [comment] 2017-01-19 15:02
<3 May the 🇺🇸 be with us!
